on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        # uses: castleodinland/build_docker_and_run@v1
        uses: actions/hello-world-docker-action@master
        with:
          who-to-greet: 'Mona the Octocat'
      
      - name: Run a nds32 command
        run: pwd
