on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: castleodinland/AndesToolChains@v1
      
      - name: Run a nds32 command
        run: |
          cd /github/workspace/
          echo "step1"
          pwd
          echo "step2"
          ls
          echo "step3"

